// ASCII char codes
#define ASCII_MINUS 45
#define ASCII_HASH 35
#define ASCII_BACKSLASH 92
#define ASCII_SLASH 47
#define ASCII_SPACE 32
#define ASCII_DOUBLE_QUOTE 34
#define ASCII_QUOTE 39
#define ASCII_ASTERISK 42
#define ASCII_COMMA 44
#define ASCII_LT 60
#define ASCII_GT 62
#define ASCII_PARENTHESES_OPEN 40
#define ASCII_PARENTHESES_CLOSE 41
#define ASCII_SQUARE_BRACKET_OPEN 91
#define ASCII_SQUARE_BRACKET_CLOSE 93
#define ASCII_CURLY_BRACKET_OPEN 123
#define ASCII_CURLY_BRACKET_CLOSE 125
#define ASCII_GRAVE 96
#define ASCII_VERTICAL_LINE 124
#define ASCII_CARET 94

#define ASCII_NL 10
#define ASCII_CR 13
