
/*
    TODO:
    - Multi-line text ?
    - Ability to use string as data parameter (call modes: FILE_LOAD, FILE_PREPROCESS, RAW)

*/

#define RECURSIVE_COUNTER_LIMIT 5

#define ERRORS_NODE "#ERRORS"
#define SOURCE_NODE "#SOURCE"

// ASCII char codes
#define ASCII_MINUS 45
#define ASCII_HASH 35
#define ASCII_BACKSLASH 92
#define ASCII_SLASH 47
#define ASCII_SPACE 32
#define ASCII_DOUBLE_QUOTE 34
#define ASCII_QUOTE 39
#define ASCII_ASTERISK 42
#define ASCII_COMMA 44
#define ASCII_LT 60
#define ASCII_GT 62
#define ASCII_PARENTHESES_OPEN 40
#define ASCII_PARENTHESES_CLOSE 41
#define ASCII_SQUARE_BRACKET_OPEN 91
#define ASCII_SQUARE_BRACKET_CLOSE 93
#define ASCII_CURLY_BRACKET_OPEN 123
#define ASCII_CURLY_BRACKET_CLOSE 125
#define ASCII_GRAVE 96

// Data types
#define INTEGER_REGEX "\d+"

#define STRING_QUOTES_ASCII [ASCII_QUOTE, ASCII_DOUBLE_QUOTE]
#define SCALAR_TYPE_REGEX "^[\s\d\.e()\-+*\/%^]*$"
#define CODE_PREFIX ASCII_CURLY_BRACKET_OPEN
#define CODE_POSTIFX ASCII_CURLY_BRACKET_CLOSE
#define ARRAY_PREFIX ASCII_SQUARE_BRACKET_OPEN
#define ARRAY_POSTFIX ASCII_SQUARE_BRACKET_CLOSE
#define HASHMAP_PREFIX ASCII_PARENTHESES_OPEN
#define HASHMAP_POSTFIX ASCII_PARENTHESES_CLOSE
#define VARIABLE_PREFIX ASCII_LT
#define VARIABLE_POSTFIX ASCII_GT
#define EVAL_PERFIX_ASCII ASCII_GRAVE
#define SIDES_MAP [\
    ["BLUFOR", west],\
    ["WEST", west],\
    ["OPFOR", east],\
    ["EAST", east],\
    ["INDEP", resistance],\
    ["INDEPENDENT", resistance],\
    ["RESISTANCE", resistance],\
    ["GUER", resistance],\
    ["CIVILIAN", civilian],\
    ["CIV", civilian] \
]

#define NIL_TYPE "nil"
#define NULL_TYPES [ \
    "objNull",\
    "grpNull",\
    "locationNull"\
]

#define REF_PREFIX ASCII_ASTERISK
#define REF_INFIX ASCII_GT

// Error codes
#define ERR_FILE_EMPTY "ERR_FILE_EMPTY"
#define ERR_FILE_NO_CONTENT "ERR_NO_CONTENT"
#define ERR_INDENT_MALFORMED "ERR_INDENT_MALFOMED"
#define ERR_INDENT_UNEXPECTED_ROOT "ERR_INDENT_UNEXPECTED_ROOT"
#define ERR_INDENT_UNEXPECTED_NESTED "ERR_INDENT_UNEXPECTED_NESTED"
#define ERR_NODE_DUPLICATE "ERR_NODE_DUPLICATE"
#define ERR_DATA_MALFORMED "ERR_DATA_MALFORMED"
#define ERR_DATA_KEYVALUEPAIR_MALFORMED "ERR_DATA_KEYVALUEPAIR_MALFORMED"
#define ERR_DATA_VALUE_MALFORMED "ERR_DATA_VALUE_MALFORMED"
#define ERR_DATA_NIL_VARIABLE_REF "ERR_DATA_NIL_VARIABLE_REF"
#define ERR_DATA_NIL_REFERENCE "ERR_DATA_NIL_REFERENCE"
#define ERR_DATA_RECURSIVE_REFERENCE "ERR_DATA_RECURSIVE_REFERENCE"
#define ERR_DATA_NAN_INDEX_REFERENECE "ERR_DATA_NAN_INDEX_REFERENECE"
