/*
Fails in test:
call compile preprocessFileLineNumbers "tests\SFMLParser\test_structure_arrays.sqf"

NestedInObject2:
    - arr:
        - 1
        - 2
        - 3
      key1: 1  # <- Fails ["ERR_INDENT_UNEXPECTED_NESTED","Unexpected indent for nested item (expected 8 but actual is 6"]
    - key2: 2

*/

// ASCII char codes
#include "ascii_codes.hpp"

// Function modes
#define MODE_FILE_LOAD "LOAD_FILE"
#define MODE_FILE_PREPROCESS "PREPROCESS_FILE"
#define MODE_PARSE_LINE "PARSE_LINE"

#define RECURSIVE_COUNTER_LIMIT 5

#define INDENT_ARRAY_NESTED 2
#define INDENT_MULTILINE 4

// System nodes of the hash
#define ERRORS_NODE "#ERRORS"
#define SOURCE_NODE "#SOURCE"
#define MULTILINE_KEY_NODE "#MULTILINE_BUFFER_KEY"
#define MULTILINE_VALUE_NODE "#MULTILINE_BUFFER_VALUE"
#define MULTILINE_INDENT_NODE "#MULTILINE_INDENT"
#define MULTILINE_MODE_NODE "#MULTILINE_MODE"
#define DATA_NODE "#DATA"




// Data types
#define INTEGER_REGEX "\d+"

#define STRING_QUOTES_ASCII [ASCII_QUOTE, ASCII_DOUBLE_QUOTE]
#define SCALAR_TYPE_REGEX "^[\s\d\.e()\-+*\/%^]*$"
#define CODE_PREFIX ASCII_CURLY_BRACKET_OPEN
#define CODE_POSTIFX ASCII_CURLY_BRACKET_CLOSE
#define ARRAY_PREFIX ASCII_SQUARE_BRACKET_OPEN
#define ARRAY_POSTFIX ASCII_SQUARE_BRACKET_CLOSE
#define HASHMAP_PREFIX ASCII_PARENTHESES_OPEN
#define HASHMAP_POSTFIX ASCII_PARENTHESES_CLOSE
#define VARIABLE_PREFIX ASCII_LT
#define VARIABLE_POSTFIX ASCII_GT
#define EXPRESSION_PERFIX_ASCII ASCII_GRAVE
#define SIDES_MAP [\
    ["BLUFOR", west],\
    ["WEST", west],\
    ["OPFOR", east],\
    ["EAST", east],\
    ["INDEP", resistance],\
    ["INDEPENDENT", resistance],\
    ["RESISTANCE", resistance],\
    ["GUER", resistance],\
    ["CIVILIAN", civilian],\
    ["CIV", civilian] \
]

#define NIL_TYPE "nil"
#define NULL_TYPES [ \
    "objNull",\
    "grpNull",\
    "locationNull"\
]

#define REF_PREFIX ASCII_ASTERISK
#define REF_INFIX ASCII_GT

// Error codes
#define ERR_MODE_UNDEFINED "ERR_MODE_UNDEFINED"
#define ERR_FILE_EMPTY "ERR_FILE_EMPTY"
#define ERR_FILE_NO_CONTENT "ERR_NO_CONTENT"
#define ERR_INDENT_MALFORMED "ERR_INDENT_MALFOMED"
#define ERR_INDENT_UNEXPECTED_ROOT "ERR_INDENT_UNEXPECTED_ROOT"
#define ERR_INDENT_UNEXPECTED_NESTED "ERR_INDENT_UNEXPECTED_NESTED"
#define ERR_NODE_DUPLICATE "ERR_NODE_DUPLICATE"
#define ERR_DATA_MALFORMED "ERR_DATA_MALFORMED"
#define ERR_DATA_KEYVALUEPAIR_MALFORMED "ERR_DATA_KEYVALUEPAIR_MALFORMED"
#define ERR_DATA_VALUE_MALFORMED "ERR_DATA_VALUE_MALFORMED"
#define ERR_DATA_NIL_VARIABLE_REF "ERR_DATA_NIL_VARIABLE_REF"
#define ERR_DATA_NIL_REFERENCE "ERR_DATA_NIL_REFERENCE"
#define ERR_DATA_RECURSIVE_REFERENCE "ERR_DATA_RECURSIVE_REFERENCE"
#define ERR_DATA_NAN_INDEX_REFERENECE "ERR_DATA_NAN_INDEX_REFERENECE"
